# Generated by Django 4.0.6 on 2022-07-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('ryear', models.IntegerField()),
            ],
        ),
    ]
