# Generated by Django 4.0.6 on 2022-07-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Completion Date')),
                ('play_history', models.CharField(choices=[('PC', 'PC'), ('Xbox', 'Xbox Series X'), ('PS5', 'Playstation 5'), ('Switch', 'Nintendo Switch')], default='PC', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
