# Generated by Django 4.0.6 on 2022-07-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_toys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toy',
            new_name='Achievement',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='toys',
            new_name='achievements',
        ),
    ]
